@baseUrl = http://127.0.0.1:8000
@token = 5|w8mJ3TuRwFQ6BhLtDOANamoSuidTNv55XJXsf6PY3f4e81e3

### Home / health check
GET {{baseUrl}}
Accept: application/json

### Listar categorías
GET {{baseUrl}}/api/categories
Accept: application/json
Authorization: Bearer {{token}}

### Registrarse
POST {{baseUrl}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "Esteban",
    "email": "perejild@gmail.com",
    "password": "123456789",
    "password_confirmation": "123456789"
}

### Login
POST {{baseUrl}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "juan@gmail.com",
    "password": "123456789"
}

### Crear categoría
POST {{baseUrl}}/api/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Varios"
}

### Crear transacción
POST {{baseUrl}}/api/transactions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "transaction_date": "2026-08-22",
    "detail": "Gastos Varios",
    "amount": 50123,
    "type": "income",
    "category_id": 1,
    "tag_ids": [1]
}

### Mostrar transacciones
GET {{baseUrl}}/api/transactions
Authorization: Bearer {{token}}

### Crear tags
POST {{baseUrl}}/api/tags
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tag1"
}
